"""add review

Revision ID: 7122dc22e6c8
Revises: c34591ff36b5
Create Date: 2025-03-27 00:00:09.709412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7122dc22e6c8'
down_revision = 'c34591ff36b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('fk_reviews_item_id_items')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    # ### end Alembic commands ###
