"""add review

Revision ID: 791e5a46cb70
Revises: 7122dc22e6c8
Create Date: 2025-03-27 00:10:17.535330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '791e5a46cb70'
down_revision = '7122dc22e6c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('customer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_reviews_customer_id_customers'), 'reviews', 'customers', ['customer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_reviews_customer_id_customers'), 'reviews', type_='foreignkey')
    op.drop_column('reviews', 'customer_id')
    # ### end Alembic commands ###
